<?php
/**
 * install_phpmailer.php — Browser-based PHPMailer Installer
 *
 * Works on any cPanel / shared hosting without SSH or Composer.
 * Protected by admin session — only logged-in admins can run it.
 *
 * USAGE:
 *   1. Visit http://yourdomain.com/vvcard/install_phpmailer.php
 *   2. Click Install
 *   3. Delete this file from your server after installation
 */
declare(strict_types=1);

require_once __DIR__ . '/helpers.php';

// ── Admin-only access ─────────────────────────────────────────
if (!isLoggedIn() || !isAdmin()) {
    http_response_code(403);
    die('Access denied. Please <a href="' . BASE_URL . 'login">log in as admin</a> first.');
}

// ── Configuration ─────────────────────────────────────────────
const PHPMAILER_VERSION = '6.9.3';
const PHPMAILER_URL     = 'https://github.com/PHPMailer/PHPMailer/archive/refs/tags/v' . PHPMAILER_VERSION . '.zip';

$vendorDir  = __DIR__ . '/vendor';
$targetDir  = $vendorDir . '/phpmailer/phpmailer';
$autoloader = $vendorDir . '/autoload.php';
$tmpZip     = sys_get_temp_dir() . '/phpmailer_' . PHPMAILER_VERSION . '.zip';

$installed  = file_exists($targetDir . '/src/PHPMailer.php');
$hasCurl    = function_exists('curl_init');
$hasZip     = class_exists('ZipArchive');
$canInstall = $hasCurl && $hasZip;

$messages   = [];
$errors     = [];

// ── Handle POST install ───────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {

    if ($_POST['action'] === 'install') {
        if (!$canInstall) {
            $errors[] = 'Your server is missing cURL or ZipArchive. Use the manual method below.';
        } else {
            try {
                // 1. Download zip via cURL
                $ch = curl_init(PHPMAILER_URL);
                curl_setopt_array($ch, [
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_FOLLOWLOCATION => true,
                    CURLOPT_SSL_VERIFYPEER => true,
                    CURLOPT_TIMEOUT        => 60,
                    CURLOPT_USERAGENT      => 'VVC-Installer/1.0',
                ]);
                $zipData = curl_exec($ch);
                $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
                $curlError = curl_error($ch);
                curl_close($ch);

                if ($zipData === false || $httpCode !== 200) {
                    throw new RuntimeException('Download failed (HTTP ' . $httpCode . '). ' . $curlError);
                }

                file_put_contents($tmpZip, $zipData);
                $messages[] = 'Downloaded PHPMailer ' . PHPMAILER_VERSION . ' (' . round(strlen($zipData) / 1024) . ' KB)';

                // 2. Extract zip
                $zip = new ZipArchive();
                if ($zip->open($tmpZip) !== true) {
                    throw new RuntimeException('Could not open downloaded zip file.');
                }

                $extractDir = sys_get_temp_dir() . '/phpmailer_extract_' . time();
                $zip->extractTo($extractDir);
                $zip->close();
                unlink($tmpZip);
                $messages[] = 'Extracted archive.';

                // 3. Find the src/ directory in the extracted zip
                $srcDir = $extractDir . '/PHPMailer-' . PHPMAILER_VERSION . '/src';
                if (!is_dir($srcDir)) {
                    // fallback: find it dynamically
                    $dirs = glob($extractDir . '/*/src', GLOB_ONLYDIR);
                    $srcDir = $dirs[0] ?? '';
                }
                if (!is_dir($srcDir)) {
                    throw new RuntimeException('Could not locate src/ directory in downloaded package.');
                }

                // 4. Create vendor directory structure
                if (!is_dir($targetDir . '/src')) {
                    mkdir($targetDir . '/src', 0755, true);
                }

                // 5. Copy the 3 required files
                $required = ['PHPMailer.php', 'SMTP.php', 'Exception.php'];
                foreach ($required as $file) {
                    $from = $srcDir . '/' . $file;
                    $to   = $targetDir . '/src/' . $file;
                    if (!file_exists($from)) {
                        throw new RuntimeException("Required file not found in package: $file");
                    }
                    copy($from, $to);
                }

                // 6. Clean up temp extraction
                array_map('unlink', glob($srcDir . '/*.php'));
                @rmdir($srcDir);
                @rmdir(dirname($srcDir));

                $messages[] = 'Copied PHPMailer.php, SMTP.php, Exception.php to vendor/';

                // 7. Create minimal vendor/autoload.php
                $autoloadContent = <<<'PHP'
<?php
/**
 * Minimal autoloader for PHPMailer (installed without Composer).
 * This file is auto-generated by install_phpmailer.php
 */
spl_autoload_register(function (string $class): void {
    $map = [
        'PHPMailer\\PHPMailer\\Exception'  => __DIR__ . '/phpmailer/phpmailer/src/Exception.php',
        'PHPMailer\\PHPMailer\\PHPMailer'  => __DIR__ . '/phpmailer/phpmailer/src/PHPMailer.php',
        'PHPMailer\\PHPMailer\\SMTP'       => __DIR__ . '/phpmailer/phpmailer/src/SMTP.php',
    ];
    if (isset($map[$class])) {
        require_once $map[$class];
    }
});
PHP;
                file_put_contents($autoloader, $autoloadContent);
                $messages[] = 'Created vendor/autoload.php';
                $installed  = true;

            } catch (RuntimeException $e) {
                $errors[] = $e->getMessage();
            }
        }
    }

    if ($_POST['action'] === 'create_autoload') {
        // User uploaded files manually — just create the autoloader
        $missing = [];
        foreach (['PHPMailer.php', 'SMTP.php', 'Exception.php'] as $f) {
            if (!file_exists($targetDir . '/src/' . $f)) {
                $missing[] = $f;
            }
        }
        if ($missing) {
            $errors[] = 'Missing files in vendor/phpmailer/phpmailer/src/ — ' . implode(', ', $missing)
                      . '. Please upload them first.';
        } else {
            $autoloadContent = <<<'PHP'
<?php
spl_autoload_register(function (string $class): void {
    $map = [
        'PHPMailer\\PHPMailer\\Exception'  => __DIR__ . '/phpmailer/phpmailer/src/Exception.php',
        'PHPMailer\\PHPMailer\\PHPMailer'  => __DIR__ . '/phpmailer/phpmailer/src/PHPMailer.php',
        'PHPMailer\\PHPMailer\\SMTP'       => __DIR__ . '/phpmailer/phpmailer/src/SMTP.php',
    ];
    if (isset($map[$class])) {
        require_once $map[$class];
    }
});
PHP;
            file_put_contents($autoloader, $autoloadContent);
            $messages[] = 'vendor/autoload.php created successfully.';
            $installed  = true;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Install PHPMailer — <?= e(siteName()) ?></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css">
    <style>
        body { background: #f0f2f5; }
        .installer-card { max-width: 720px; margin: 2rem auto; }
        .check-ok   { color: #22c55e; }
        .check-fail { color: #ef4444; }
        pre { background: #1e1e2e; color: #cdd6f4; padding: 1rem; border-radius: 8px; font-size: .8rem; overflow-x: auto; }
    </style>
</head>
<body class="p-4">
<div class="installer-card">
    <div class="card border-0 shadow-sm">
        <div class="card-header bg-primary text-white p-4">
            <h4 class="mb-1 fw-bold"><i class="fas fa-envelope me-2"></i>PHPMailer Installer</h4>
            <p class="mb-0 opacity-75 small">Installs PHPMailer <?= PHPMAILER_VERSION ?> for email support (password resets &amp; invitations)</p>
        </div>
        <div class="card-body p-4">

            <?php if ($messages): ?>
                <div class="alert alert-success">
                    <?php foreach ($messages as $m): ?>
                        <div><i class="fas fa-check-circle me-1"></i><?= e($m) ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if ($errors): ?>
                <div class="alert alert-danger">
                    <?php foreach ($errors as $err): ?>
                        <div><i class="fas fa-times-circle me-1"></i><?= e($err) ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php if ($installed): ?>
                <!-- ── Already installed ────────────────────────── -->
                <div class="alert alert-success text-center py-4">
                    <i class="fas fa-check-circle fa-3x d-block mb-3"></i>
                    <h5 class="fw-bold">PHPMailer is installed and ready!</h5>
                    <p class="mb-0">Configure your SMTP credentials in
                        <a href="<?= BASE_URL ?>admin/settings/?tab=smtp" class="fw-semibold">
                            Admin → Settings → SMTP
                        </a>
                    </p>
                </div>
                <div class="alert alert-warning d-flex align-items-center">
                    <i class="fas fa-exclamation-triangle me-3 fa-lg"></i>
                    <div>
                        <strong>Security:</strong> Delete this file from your server now.
                        It is no longer needed and should not remain accessible.
                        <br>Path: <code><?= e(__FILE__) ?></code>
                    </div>
                </div>
                <div class="text-center mt-3">
                    <a href="<?= BASE_URL ?>admin/settings/?tab=smtp" class="btn btn-primary me-2">
                        <i class="fas fa-cog me-1"></i>Configure SMTP
                    </a>
                    <a href="<?= BASE_URL ?>admin/" class="btn btn-outline-secondary">
                        Back to Admin
                    </a>
                </div>

            <?php else: ?>

                <!-- ── Server capability check ──────────────────── -->
                <h6 class="fw-bold mb-3">Server Capabilities</h6>
                <table class="table table-sm mb-4">
                    <tbody>
                        <tr>
                            <td><i class="<?= $hasCurl ? 'check-ok fas fa-check' : 'check-fail fas fa-times' ?> me-2"></i>
                                <strong>cURL</strong></td>
                            <td class="text-muted small"><?= $hasCurl ? 'Available — can download PHPMailer automatically' : 'Not available — use manual install below' ?></td>
                        </tr>
                        <tr>
                            <td><i class="<?= $hasZip ? 'check-ok fas fa-check' : 'check-fail fas fa-times' ?> me-2"></i>
                                <strong>ZipArchive</strong></td>
                            <td class="text-muted small"><?= $hasZip ? 'Available — can extract zip automatically' : 'Not available — use manual install below' ?></td>
                        </tr>
                    </tbody>
                </table>

                <?php if ($canInstall): ?>
                <!-- ── Auto install ──────────────────────────────── -->
                <div class="card border-success border mb-4">
                    <div class="card-header bg-success text-white fw-semibold">
                        <i class="fas fa-magic me-2"></i>Option A — Automatic Install (Recommended)
                    </div>
                    <div class="card-body p-4">
                        <p class="text-muted small mb-3">
                            Downloads PHPMailer <?= PHPMAILER_VERSION ?> from GitHub and installs it automatically.
                            No SSH or Composer needed.
                        </p>
                        <form method="POST">
                            <input type="hidden" name="action" value="install">
                            <button type="submit" class="btn btn-success">
                                <i class="fas fa-download me-1"></i>Download &amp; Install PHPMailer
                            </button>
                        </form>
                    </div>
                </div>
                <?php endif; ?>

                <!-- ── Manual install ────────────────────────────── -->
                <div class="card border mb-4">
                    <div class="card-header fw-semibold bg-light">
                        <i class="fas fa-upload me-2"></i>Option <?= $canInstall ? 'B' : 'A' ?> — Manual Install via cPanel File Manager
                    </div>
                    <div class="card-body p-4">
                        <ol class="small mb-4">
                            <li class="mb-2">
                                Download PHPMailer from GitHub:<br>
                                <a href="https://github.com/PHPMailer/PHPMailer/archive/refs/tags/v<?= PHPMAILER_VERSION ?>.zip"
                                   target="_blank" class="btn btn-sm btn-outline-primary mt-1">
                                    <i class="fas fa-download me-1"></i>Download PHPMailer <?= PHPMAILER_VERSION ?> ZIP
                                </a>
                            </li>
                            <li class="mb-2">
                                In <strong>cPanel File Manager</strong>, create this folder inside your project:
                                <pre>vvcard/vendor/phpmailer/phpmailer/src/</pre>
                            </li>
                            <li class="mb-2">
                                From the downloaded zip, extract and upload only these 3 files into that folder:
                                <pre>PHPMailer-<?= PHPMAILER_VERSION ?>/src/PHPMailer.php
PHPMailer-<?= PHPMAILER_VERSION ?>/src/SMTP.php
PHPMailer-<?= PHPMAILER_VERSION ?>/src/Exception.php</pre>
                            </li>
                            <li>
                                Once uploaded, click the button below to create the autoloader file:
                            </li>
                        </ol>
                        <form method="POST">
                            <input type="hidden" name="action" value="create_autoload">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-wrench me-1"></i>Create vendor/autoload.php
                            </button>
                        </form>
                    </div>
                </div>

                <!-- ── cPanel Terminal ───────────────────────────── -->
                <div class="card border mb-0">
                    <div class="card-header fw-semibold bg-light">
                        <i class="fas fa-terminal me-2"></i>Option <?= $canInstall ? 'C' : 'B' ?> — cPanel Terminal (if available)
                    </div>
                    <div class="card-body p-4">
                        <p class="small text-muted mb-2">In cPanel → <strong>Advanced → Terminal</strong>:</p>
                        <pre>cd ~/public_html/vvcard
bash install.sh</pre>
                        <p class="small text-muted mb-0">
                            Or if Composer is available globally:
                        </p>
                        <pre>cd ~/public_html/vvcard
composer install --no-dev</pre>
                    </div>
                </div>

            <?php endif; ?>
        </div>
    </div>

    <p class="text-center text-muted small mt-3">
        <a href="<?= BASE_URL ?>admin/" class="text-muted">← Back to Admin Panel</a>
    </p>
</div>
</body>
</html>
